### ISSUE TITLE
UndefVarError: mapclimgrid not defined

### ISSUE THREAD

**Issue by cvitolo** [JuliaClimate/ClimateTools.jl#121]
Hello! I'm trying to reproduce your example [here](https://balinus.github.io/ClimateTools.jl/dev/examples/) but when I try to run 

`mapclimgrid(model, region = "Quebec")`

I get the following error:

`UndefVarError: mapclimgrid not defined`

Any idea what I'm doing wrong?

**Comment by Balinus** [comment]
Hello!

Yes, the package is being splitted across 3 new packages : [ClimateBase](https://github.com/JuliaClimate/ClimateBase.jl) (invisible to the end-user), ClimateTools and [ClimatePlots](https://github.com/JuliaClimate/ClimatePlots.jl). The docs have not yet been updated to reflect this new change that occurred this weekend.

They are all registered now so I assume you have version 0.16 of ClimateTools? If that's the case, add ClimatePlots:

```julia
using Pkg; Pkg.add("ClimatePlots")
using ClimatePlots
mapclimgrid(model, region = "Quebec")
```

Hopefully, this should work. Do not forget to configure PyCall accordingly: https://balinus.github.io/ClimateTools.jl/stable/installation/

**Comment by cvitolo** [comment]
Thanks for the prompt response @Balinus !

Followed your instructions but I now get a different error:

`ArgumentError: ref of NULL PyObject

Stacktrace:
 [1] getproperty(::PyObject, ::String) at /home/claudia/.julia/packages/PyCall/ttONZ/src/PyCall.jl:303
 [2] getproperty at /home/claudia/.julia/packages/PyCall/ttONZ/src/PyCall.jl:313 [inlined]
 [3] #mapclimgrid#2(::String, ::Bool, ::Float64, ::Float64, ::Float64, ::Float64, ::typeof(mapclimgrid)) at /home/claudia/.julia/packages/ClimatePlots/He93M/src/mapping.jl:150
 [4] (::ClimatePlots.var"#kw##mapclimgrid")(::NamedTuple{(:region, :states, :llon, :rlon, :slat, :nlat),Tuple{String,Bool,Float64,Float64,Float64,Float64}}, ::typeof(mapclimgrid)) at ./none:0
 [5] #mapclimgrid#1(::String, ::Bool, ::Array{Any,1}, ::Int64, ::Array{Any,1}, ::Array{Any,1}, ::Tuple{Float64}, ::Tuple{Float64}, ::String, ::Symbol, ::String, ::Int64, ::Bool, ::String, ::String, ::typeof(mapclimgrid), ::ClimGrid{AxisArrays.AxisArray{Float32,3,Array{Float32,3},Tuple{AxisArrays.Axis{:lon,Array{Float64,1}},AxisArrays.Axis{:lat,Array{Float64,1}},AxisArrays.Axis{:time,Array{Union{Missing, DateTimeNoLeap},1}}}}}) at /home/claudia/.julia/packages/ClimatePlots/He93M/src/mapping.jl:96
 [6] (::ClimatePlots.var"#kw##mapclimgrid")(::NamedTuple{(:region,),Tuple{String}}, ::typeof(mapclimgrid), ::ClimGrid{AxisArrays.AxisArray{Float32,3,Array{Float32,3},Tuple{AxisArrays.Axis{:lon,Array{Float64,1}},AxisArrays.Axis{:lat,Array{Float64,1}},AxisArrays.Axis{:time,Array{Union{Missing, DateTimeNoLeap},1}}}}}) at ./none:0
 [7] top-level scope at In[16]:1`

**Comment by Balinus** [comment]
Do you have a link to the netCDF file? I'll try it on my end.

**Comment by cvitolo** [comment]
It seems `mpl_toolkits.basemap` is not properly installed.

When I run:
```julia
using PyCall
basemap = pyimport("mpl_toolkits.basemap")
```
I get:

```
PyError (PyImport_ImportModule) <class 'FileNotFoundError'>
FileNotFoundError(2, 'No such file or directory')
  File "/home/claudia/anaconda3/envs/ClimateTools/lib/python3.6/site-packages/mpl_toolkits/basemap/__init__.py", line 156, in <module>
    epsgf = open(os.path.join(pyproj_datadir,'epsg'))
```

I'll go through the installation instructions again to see if I missed anything

**Comment by Balinus** [comment]
Just tried the installation steps and found a particular settings and I was able to reproduce your error.

When following the installation steps, it appears that we need Basemap from conda-forge repo and telling `-c conda-forge` is not enough. Otherwise, basemap installs an incompatible version of proj4 along the way.

Here's some new steps to avoid this problem. The idea is to use `strict-channel-priority`

Inside the bash terminal:

```bash
conda create --name ClimateTools python=3.6 conda
conda activate ClimateTools
conda install -c conda-forge matplotlib --strict-channel-priority
conda install -c conda-forge basemap --strict-channel-priority
conda install -c conda-forge basemap-data-hires --strict-channel-priority
conda install -c conda-forge cmocean --strict-channel-priority
```

If it works on your side, I'll update the installation documentation.

edit - I also followed those steps, but I'm not sure it was necessary: https://conda-forge.org/docs/user/tipsandtricks.html#how-to-fix-it

**Comment by fidelthomet** [comment]
I'm having similar issues and following your steps @Balinus did not work for me…

When I run `using ClimatePlots` i now get the following error
```
ERROR: InitError: Failed to import required Python module mpl_toolkits.basemap.

For automated mpl_toolkits.basemap installation, try configuring PyCall to use the Conda.jl package's Python "Miniconda" distribution within Julia. Relaunch Julia and run:
    ENV["PYTHON"]=""
    Pkg.build("PyCall")
before trying again.

Note that Conda.jl can use custom conda environment. Read more about `CONDA_JL_HOME` configuration in Conda.jl documentation:
    https://github.com/JuliaPy/Conda.jl

To install basemap using /Users/fidel/.miniconda3/envs/ClimateTools/bin/conda, you can run the following command from your system shell:
    /Users/fidel/.miniconda3/envs/ClimateTools/bin/conda install basemap

The pyimport exception was: PyError (PyImport_ImportModule) <class 'KeyError'>
KeyError('PROJ_LIB',)
  File "/Users/fidel/.miniconda3/envs/ClimateTools/lib/python3.6/site-packages/mpl_toolkits/basemap/__init__.py", line 152, in <module>
    pyproj_datadir = os.environ['PROJ_LIB']
  File "/Users/fidel/.miniconda3/envs/ClimateTools/lib/python3.6/os.py", line 669, in __getitem__
    raise KeyError(key) from None
```

I have checked that basemap is available in my conda env. My Julia code is as follows
```
using PyCall
ENV["PYTHON"]="/Users/fidel/.miniconda3/envs/ClimateTools/bin/python"
using Pkg; Pkg.build("PyCall")

using ClimateTools
using ClimatePlots
```

**Comment by Balinus** [comment]
Can you post a `conda list` of your miniconda env?

**Comment by fidelthomet** [comment]
```
# Name                    Version                   Build  Channel
basemap                   1.2.1            py36hd2746df_2    conda-forge
basemap-data-hires        1.2.1                         0    conda-forge
ca-certificates           2019.11.28           hecc5488_0    conda-forge
certifi                   2019.11.28               py36_0    conda-forge
cffi                      1.13.2           py36h33e799b_0    conda-forge
chardet                   3.0.4                 py36_1003    conda-forge
cmocean                   2.0                        py_3    conda-forge
colorspacious             1.1.2              pyh24bf2e0_0    conda-forge
conda                     4.8.2                    py36_0    conda-forge
conda-package-handling    1.6.0            py36h0b31af3_1    conda-forge
cryptography              2.8              py36hafa8578_1    conda-forge
cycler                    0.10.0                     py_2    conda-forge
freetype                  2.10.0               h24853df_1    conda-forge
geos                      3.8.0                h4a8c4bd_0    conda-forge
idna                      2.8                   py36_1000    conda-forge
kiwisolver                1.1.0            py36ha1b3eb9_0    conda-forge
libblas                   3.8.0               14_openblas    conda-forge
libcblas                  3.8.0               14_openblas    conda-forge
libcxx                    9.0.1                         1    conda-forge
libffi                    3.2.1             h6de7cb9_1006    conda-forge
libgfortran               4.0.0                         2    conda-forge
liblapack                 3.8.0               14_openblas    conda-forge
libopenblas               0.3.7                h3d69b6c_7    conda-forge
libpng                    1.6.37               h2573ce8_0    conda-forge
llvm-openmp               9.0.1                h28b9765_2    conda-forge
matplotlib                3.1.3                    py36_0    conda-forge
matplotlib-base           3.1.3            py36h11da6c2_0    conda-forge
ncurses                   6.1               h0a44026_1002    conda-forge
numpy                     1.18.1           py36hde6bac1_0    conda-forge
openssl                   1.1.1d               h0b31af3_0    conda-forge
pip                       20.0.2                   py36_1    conda-forge
proj4                     5.2.0             h6de7cb9_1006    conda-forge
pycosat                   0.6.3           py36h0b31af3_1002    conda-forge
pycparser                 2.19                     py36_1    conda-forge
pyopenssl                 19.1.0                   py36_0    conda-forge
pyparsing                 2.4.6                      py_0    conda-forge
pyproj                    1.9.6           py36h0b31af3_1002    conda-forge
pyshp                     2.1.0                      py_0    conda-forge
pysocks                   1.7.1                    py36_0    conda-forge
python                    3.6.7             h4285619_1006    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
readline                  8.0                  hcfe32e1_0    conda-forge
requests                  2.22.0                   py36_1    conda-forge
ruamel_yaml               0.15.80         py36h0b31af3_1000    conda-forge
setuptools                45.1.0                   py36_0    conda-forge
six                       1.14.0                   py36_0    conda-forge
sqlite                    3.30.1               h93121df_0    conda-forge
tk                        8.6.10               hbbe82c9_0    conda-forge
tornado                   6.0.3            py36h0b31af3_0    conda-forge
tqdm                      4.42.1                     py_0    conda-forge
urllib3                   1.25.7                   py36_0    conda-forge
wheel                     0.34.2                   py36_0    conda-forge
xz                        5.2.4             h1de35cc_1001    conda-forge
yaml                      0.2.2                h0b31af3_1    conda-forge
zlib                      1.2.11            h0b31af3_1006    conda-forge
```

**Comment by Balinus** [comment]
Did you tried exiting julia and re-entering? Since you already loaded PyCall before building it, perhaps it is pointing to the last PyCall config?

When you say that basemap is available in your conda env, you successfully loaded the module in python?

**Comment by Balinus** [comment]
So i re-tried the proposed steps and did not had a problem with loading ClimatePlots and/or ClimateTools.

The `PROJ_LIB` error is not new I must admit, in the sense that I already encountered it. 

Another idea: did you activated your conda env before entering Julia and building PyCall? This should not matter, but perhaps it plays on some env variables. For instance, what does the following commands return?

`echo $PROJ_LIB`
`echo $CONDA_PREFIX`

**Comment by fidelthomet** [comment]
> Did you tried exiting julia and re-entering? Since you already loaded PyCall before building it, perhaps it is pointing to the last PyCall config?

Yes, I just tried again, also without `using PyCall` first. But it doesn't make a difference

> When you say that basemap is available in your conda env, you successfully loaded the module in python?

Yes

**Comment by fidelthomet** [comment]
```
echo $PROJ_LIB
/Users/fidel/.miniconda3/envs/ClimateTools/share/proj
echo $CONDA_PREFIX
/Users/fidel/.miniconda3/envs/ClimateTools
```

**Comment by fidelthomet** [comment]
Thank you very much for your support so far. I'll try to have a fresh look at it tomorrow or on Friday and will let you know what I find out

**Comment by Balinus** [comment]
No problem. I feel responsible since I chose basemap as the back-end for plotting! :/

Meanwhile, I'm gonna explore if I can switch to cartopy in the coming weeks.

**Comment by Balinus** [comment]
This is probably solved by https://github.com/JuliaClimate/ClimatePlots.jl/releases/tag/v0.2.0
