### ISSUE TITLE
Computing climatologies

### ISSUE THREAD

**Issue by juliohm** [JuliaClimate/ClimateTools.jl#158]
I am new to climate sciences so forgive me if this is not an appropriate question for the project.

Is it possible to compute climatologies given a NetCDF file with a time series of climate data like in https://apps.ecmwf.int/static/wmolcdnv/docs/daily_climatology_description.pdf?

**Comment by Balinus** [comment]
Daily climatologies are not implemented currently in ClimateTools. It shouldn't be too hard to implement though.

We need to add a method for function [resample](https://github.com/JuliaClimate/ClimateTools.jl/blob/1fa0b9cc78f275b1791ae63097aacba4b2a937db/src/time.jl#L8) where we define `day` and `size_window`. Then loop over all available julian day in the provided ClimGrid (i.e. netCDF file) and do a weighted mean (+ other statistics of interest) of the window around the julian day (including all years). 

The building block for extracting all index for a given julian day and a moving window for all available year is already present in the bias correction function [qqmap](https://github.com/JuliaClimate/ClimateTools.jl/blob/1fa0b9cc78f275b1791ae63097aacba4b2a937db/src/biascorrect.jl#L143). 

I guess the only function not yet defined would be the weights, but this should not be difficult.

I could probably sketch something by the end of June or I can help you along the way if you are in a hurry. It would not take a lot of time to do it, but with the pandemic, I have my 3 childrens at home, hence not a lot of free time.

**Comment by juliohm** [comment]
Thank you @Balinus , I will review what I need to do more carefully and will come back if this is blocking other activities. Hopefully I will be able to contribute to the package 👍

**Comment by Balinus** [comment]
Great! That would be a great addition and is inline with the package objectives.

**Comment by juliohm** [comment]
We have other ways to compute means over time series of images nowadays. Closing the issue.
