### ISSUE TITLE
Installation and Basemap dependency 

### ISSUE THREAD

**Issue by dmetivie** [JuliaClimate/ClimateTools.jl#208]
I tried to install `ClimateTools.jl` which worked with `]add ClimateTools`. 
However, at my first 
`using ClimateTools`
it seems like it tries to install `basemap` with Conda, which fails because apparently `basemap `is not compatible with `python3.9`.
```
[ Info: Installing mpl_toolkits.basemap via the Conda basemap package...
[ Info: Running `conda install -y basemap` in root environment
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: / 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                              

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - basemap -> python[version='>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0']

Your python: python=3.9

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.
```

From what I read it sounded like `basemap` was not required by `ClimateTools.jl` so I don't understand why this happens.

**Comment by dmetivie** [comment]
It seems that I needed to also install `]add ClimatePlots`. Then 
```
using ClimateTools
using ClimatePlots
```
works!

Maybe it should be clarified in the doc (or I missed something). Anyway, the `basemap` call is strange, and I cannot find where it comes from in the files.

BTW in the [doc](https://juliaclimate.github.io/ClimateTools.jl/stable/installation/#Approach-no.-1-Use-Anaconda-or-main-system-python-distribution-1) I think there is a typo, it says `basemap` instead of `cartopy`.

Thanks for the amazing work!

**Comment by Balinus** [comment]
Thanks for the info! 

Indeed, it is strange. Can you tell me which version of ClimateTools was installed when you first tried to install the package? on my side, in a fresh environment, there is no error or basemap dependency. Note that Basemap was a dependency in earlier versions.

**Comment by dmetivie** [comment]
In a fresh environment, I also do not get any issues.
In my default environment where I get the `basemap` dependency, it installs v0.13.0. 
Is it related to the fact that most of my packages are downgraded when I install ClimateTools ?

**Comment by Balinus** [comment]
Yes, I think so. I need to update ClimateTools dependencies, this would help surely! However, you should always define a new environment for your projects. I often have multiple environment for a single projects. it is more upfront work but it is much simpler in the end.
