### ISSUE TITLE
Dependency updates needed

### ISSUE THREAD

**Issue by gaelforget** [JuliaClimate/ClimateTools.jl#226]
1. Currently ClimateTools.jl conflicts with ClimateBase.jl > 0.6 cause 0.7 removed the ClimGrid type and functionalities.

In [JuliaClimate/Notebooks](https://github.com/JuliaClimate/Notebooks), I wanted to demo ClimateTools.jl and ClimateBase.jl together in [this notebook](https://juliaclimate.github.io/Notebooks/NetCDF_packages.html) as the ClimateBase.jl docs state that they are related. 

But it seems that I cannot simply do that, owing in part to the conflict noted above. 

For now, a simple solution to this would be to copy the ClimGrid type and functionalities that were removed from ClimateBase.jl in 0.7 back into ClimateTools.jl, and then remove the ClimateBase.jl 0.6 dependency in ClimateTools.jl 

See https://github.com/gaelforget/ClimateTools.jl/tree/update_dependencies_gf1 

This prompted me to look at ClimateTools dependencies in more detail.

2. InverseDistanceWeighting.jl is not used and was deprecated in favor of [GeoEstimation.jl](https://github.com/JuliaEarth/GeoEstimation.jl) in 2020.

Solution : InverseDistanceWeighting.jl can just be removed 

3.  Extremes.jl has a Manifest.toml file in the repo and conflicts with other packages

Removing the Manifest.toml from Extremes.jl as done in https://github.com/gaelforget/Extremes.jl/tree/rm_Manifest_toml should help.

For now in https://github.com/gaelforget/ClimateTools.jl/tree/update_dependencies_gf1 just removes the dependency to Extremes.jl and omits related test + code.

### next steps?

The above patches allow for passing all of the ClimateTools.jl tests with updated dependencies on Julia 1.6 and 1.8 

See https://github.com/gaelforget/ClimateTools.jl/actions/runs/3041967989

To me this would seem like a useful step forward given that ClimateTools.jl seems stuck at v0.23.1 from Sept 2021 and is becoming hard to use in concert with other packages. 

Merging https://github.com/gaelforget/ClimateTools.jl/tree/update_dependencies_gf1 would at least allow using ClimateTools.jl and the up to date ClimateBase.jl at the same time. This could in fact help progress on the stated goal of ClimateBase.jl supporting ClimateTools.jl in the future.

With regard to Extremes.jl, I will send a PR to them and am hopeful we would just be able to bring back their next release as a dependency in ClimateTools.jl , in order to undo that part of https://github.com/gaelforget/ClimateTools.jl/tree/update_dependencies_gf1

**Comment by Balinus** [comment]
Hello @gaelforget, this is really appreciated!

George Datseris took over ClimateBase.jl ~2 years ago and I was not able to keep it up with my new job. Moving back what was moved into ClimateBase.jl seems like a good fix, while trying to update ClimateTools.jl to conform to the new ClimateBase.jl.

I will take a look at your proposal and try to update everything in coming weeks. I have some work I need to do for an peer-reviwed article and I should be able to spend time on ClimateTools.jl.

Best regards!

**Comment by Balinus** [comment]
Also, I think Extremes.jl moved to an org : https://github.com/JuliaExtremes/Extremes.jl

**Comment by deszoeke** [comment]
CSV v6.0.1 is not compiling in ClimateTools. I think this is a specific example of this issue.

CSV works in some other julia packages I regularly update, but ClimateTools downgrades it and breaks it and its dependencies.

Activating a local environment also doesn't work:
```julia
]activate ClimateTools
]add ClimateTools
]status
Status `~/Projects/ASTRAL/era5/ClimateTools/Project.toml`
  [4f4ee721] ClimateTools v0.23.1
]precompile

ERROR: The following 1 direct dependency failed to precompile:

ClimateTools [4f4ee721-4970-5af2-8560-6c1d960e3231]

Failed to precompile ClimateTools [4f4ee721-4970-5af2-8560-6c1d960e3231] to /Users/sdeszoek/.julia/compiled/v1.8/ClimateTools/jl_f96Xcw.
ERROR: LoadError: ccall method definition: argument 1 type doesn't correspond to a C type
Stacktrace:
 [1] top-level scope
   @ ~/.julia/packages/CSV/76SRf/src/utils.jl:382
 [2] include(mod::Module, _path::String)
   @ Base ./Base.jl:419
 [3] include(x::String)
   @ CSV ~/.julia/packages/CSV/76SRf/src/CSV.jl:1
 [4] top-level scope
   @ ~/.julia/packages/CSV/76SRf/src/CSV.jl:14
 [5] include
   @ ./Base.jl:419 [inlined]
 [6] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::String)
   @ Base ./loading.jl:1554
 [7] top-level scope
   @ stdin:1
in expression starting at /Users/sdeszoek/.julia/packages/CSV/76SRf/src/utils.jl:382
in expression starting at /Users/sdeszoek/.julia/packages/CSV/76SRf/src/CSV.jl:1
in expression starting at stdin:1
ERROR: LoadError: Failed to precompile CSV [336ed68f-0bac-5ca0-87d4-7b16caf5d00b] to /Users/sdeszoek/.julia/compiled/v1.8/CSV/jl_Vdnpxr.
Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:35
  [2] compilecache(pkg::Base.PkgId, path::String, internal_stderr::IO, internal_stdout::IO, keep_loaded_modules::Bool)
    @ Base ./loading.jl:1707
  [3] compilecache
    @ ./loading.jl:1651 [inlined]
  [4] _require(pkg::Base.PkgId)
    @ Base ./loading.jl:1337
  [5] _require_prelocked(uuidkey::Base.PkgId)
    @ Base ./loading.jl:1200
  [6] macro expansion
    @ ./loading.jl:1180 [inlined]
  [7] macro expansion
    @ ./lock.jl:223 [inlined]
  [8] require(into::Module, mod::Symbol)
    @ Base ./loading.jl:1144
  [9] include
    @ ./Base.jl:419 [inlined]
 [10] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::String)
    @ Base ./loading.jl:1554
 [11] top-level scope
    @ stdin:1
in expression starting at /Users/sdeszoek/.julia/packages/GeoStatsBase/mjRHZ/src/GeoStatsBase.jl:5
in expression starting at stdin:1
ERROR: LoadError: Failed to precompile GeoStatsBase [323cb8eb-fbf6-51c0-afd0-f8fba70507b2] to /Users/sdeszoek/.julia/compiled/v1.8/GeoStatsBase/jl_TX5MI7.
Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:35
  [2] compilecache(pkg::Base.PkgId, path::String, internal_stderr::IO, internal_stdout::IO, keep_loaded_modules::Bool)
    @ Base ./loading.jl:1707
  [3] compilecache
    @ ./loading.jl:1651 [inlined]
  [4] _require(pkg::Base.PkgId)
    @ Base ./loading.jl:1337
  [5] _require_prelocked(uuidkey::Base.PkgId)
    @ Base ./loading.jl:1200
  [6] macro expansion
    @ ./loading.jl:1180 [inlined]
  [7] macro expansion
    @ ./lock.jl:223 [inlined]
  [8] require(into::Module, mod::Symbol)
    @ Base ./loading.jl:1144
  [9] include
    @ ./Base.jl:419 [inlined]
 [10] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::String)
    @ Base ./loading.jl:1554
 [11] top-level scope
    @ stdin:1
in expression starting at /Users/sdeszoek/.julia/packages/GeoStats/jacmV/src/GeoStats.jl:5
in expression starting at stdin:1
ERROR: LoadError: Failed to precompile GeoStats [dcc97b0b-8ce5-5539-9008-bb190f959ef6] to /Users/sdeszoek/.julia/compiled/v1.8/GeoStats/jl_nBvrek.
Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:35
  [2] compilecache(pkg::Base.PkgId, path::String, internal_stderr::IO, internal_stdout::IO, keep_loaded_modules::Bool)
    @ Base ./loading.jl:1707
  [3] compilecache
    @ ./loading.jl:1651 [inlined]
  [4] _require(pkg::Base.PkgId)
    @ Base ./loading.jl:1337
  [5] _require_prelocked(uuidkey::Base.PkgId)
    @ Base ./loading.jl:1200
  [6] macro expansion
    @ ./loading.jl:1180 [inlined]
  [7] macro expansion
    @ ./lock.jl:223 [inlined]
  [8] require(into::Module, mod::Symbol)
    @ Base ./loading.jl:1144
  [9] include
    @ ./Base.jl:419 [inlined]
 [10] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::Nothing)
    @ Base ./loading.jl:1554
 [11] top-level scope
    @ stdin:1
in expression starting at /Users/sdeszoek/.julia/packages/ClimateTools/EOz80/src/ClimateTools.jl:1
in expression starting at stdin:1

julia> versioninfo()
Julia Version 1.8.5
Commit 17cfb8e65ea (2023-01-08 06:45 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin21.4.0)
  CPU: 8 × Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, skylake)
  Threads: 1 on 8 virtual cores
```

**Comment by Balinus** [comment]
Thanks, a dependency cleanup is almost ready.

**Comment by Balinus** [comment]
The version v.0.24 should fixes dependencies problems. They all have been updated and modifications have been done accordingly. Cheers!
